### PR TITLE
Typo in dependency on MeasureIt.Core

### PR DESCRIPTION
**Pull request by slabarque**
The dependency resolution fails, and I cannot install the package because of this.

### CODE REVIEW

**Comment by mwpowellhtx** [comment]
@slabarque My mistake. How silly of me.

I imagine you've had a look at the library in the meanwhile. In the interest of constructive feedback, how did you find it otherwise? How did you come by it, how do you like it, etc?

Thanks!

**Comment by mwpowellhtx** [comment]
Thanks for pointing that out! Will follow up on [expanding the dependency version ranges a bit](issues/2) to more sensible ones.

**Comment by mwpowellhtx** [comment]
@slabarque Just following up here. Trying to publish to NuGet, but it is throwing error 400 in response. Working that out. Until then you should be able to pull locally, build and pack for local distribution. Thanks again!

**Comment by mwpowellhtx** [comment]
@slabarque NuGet should be updated with latest packages now. Let me know if there are any further hiccups. Thanks!

**Comment by slabarque** [comment]
Thanks for accepting. I stumbled upon your library while googling for "Autofac instrumentation". I needed a quick solution to do some performance monitoring on some of my dependencies.
Because I could not install the Nuget package, I didn't look into in further. 
I tried installing the new version you packed but I get build errors now so I still have the impression something is not quite right with the nuget packages as I'm getting the error: "Could not load file or assembly 'MeasureIt.Core, Version=1.16.0.31872, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified."
But the reference in my project is to version 1.16.0.37684

Furthermore it think the library looks interesting, however since it requires the use of attributes, it forces the classes I wish to instrument to take a dependency on the library. Would be nice if I could configure that from outside of the class (during container configuration, or just instrument all methods by default...)

**Comment by mwpowellhtx** [comment]
@slabarque Which top-level dependency (or dependencies) are you trying to take?  Are you building 32-bit or 64-bit? MeasureIt targets "Any CPU", but it is also built against .NET Framework 4.5. Or some conflict similar to that. As for dependencies, MeasureIt.Core itself does not take any dependencies, so I'm wondering is it a conflict in a target or architecture.

Yes, you are correct. At the moment MeasureIt requires invasive code, attributes, to decorate the method(s) that you'd like to instrument. I could see something potentially around an Expressions based instrumentation utilizing the MeasureIt core framework. Something like that, even. Let me think on that a little bit.

Short of that, Issues are welcome. I can't promise exactly when I might get to it, though. PRs welcome.

**Pull request merged**
